#ifndef INCLUDE_MASHIRO_KINECT_MANAGER_H_
#define INCLUDE_MASHIRO_KINECT_MANAGER_H_

namespace Mashiro {
namespace Kinect {

enum SkeletonIndex {	
		SKELETON_INDEX_HIP_CENTER,
		SKELETON_INDEX_SPINE,
		SKELETON_INDEX_SHOULDER_CENTER,
		SKELETON_INDEX_HEAD,
		SKELETON_INDEX_SHOULDER_LEFT,
		SKELETON_INDEX_ELBOW_LEFT,
		SKELETON_INDEX_WRIST_LEFT,
		SKELETON_INDEX_HAND_LEFT,
		SKELETON_INDEX_SHOULDER_RIGHT,
		SKELETON_INDEX_ELBOW_RIGHT,
		SKELETON_INDEX_WRIST_RIGHT,
		SKELETON_INDEX_HAND_RIGHT,
		SKELETON_INDEX_HIP_LEFT,
		SKELETON_INDEX_KNEE_LEFT,
		SKELETON_INDEX_ANKLE_LEFT,
		SKELETON_INDEX_FOOT_LEFT,
		SKELETON_INDEX_HIP_RIGHT,
		SKELETON_INDEX_KNEE_RIGHT,
		SKELETON_INDEX_ANKLE_RIGHT,
		SKELETON_INDEX_FOOT_RIGHT,
		SKELETON_INDEX_NONE,
    };

}
}

#endif
